---
title: "Goochland_Land_Plot"
output: html_document
date: '2022-06-27'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
```

```{r}
Goochland <- read.csv("C:/Users/Christopher Vest/Documents/Land_use_project/Goochland_info/2022_goochland.csv")

Goochland2018 <- read.csv("C:/Users/Christopher Vest/Documents/Land_use_project/Goochland_info/2018_goochland.csv")
```

```{r}
land_use.df <- Goochland2018 %>% group_by(LUC) %>% summarise(total_acre = sum(Total.Land, na.rm = TRUE))
ggplot(land_use.df, aes(x =reorder(LUC, total_acre), y = total_acre, fill = LUC)) + geom_bar(stat = "identity") + theme(legend.position = "none") + coord_flip() + scale_fill_viridis_d() +labs(title = "Total Acreage by Land Use (Goochland 2018)", y = "Total Acres", x= "Land Use", caption = "Source: Administrative Data from Goochland County") + geom_text(aes(label = round(total_acre, 2)), hjust = -.1) + ylim(0, 67500)
```
```{r}
lu_count.df <- Goochland %>% group_by(LUC) %>% count(LUC)
ggplot(lu_count.df, aes(x =reorder(LUC, n), y = n, fill = LUC)) + geom_bar(stat = "identity") + theme(legend.position = "none") + coord_flip() + scale_fill_viridis_d()  +labs(title = "Number of Parcels by Land Use (Goochland 2018)", y = "Number of Parcels", x= "Land Use", caption = "Source: Administrative Data from Goochland County")+ geom_text(aes(label = round(n, 2)), hjust = -.1) + ylim(0, 12000)
```

