---
title: "Land_Use_Census_Data"
author: "NDP"
date: '2022-06-13'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("/Users/christophervest/Documents/Land_use_project")
```

```{r set_up_API, }
readRenviron("~/.Renviron") #readin Census API key
Sys.getenv("census_api_key") #confirm you have read in your Census API key
```


```{r}
Year <-  2020
```


```{r}
library(tidyverse)
library(tidycensus)
Goochland_VA_population_2020 <- get_acs(geography = "tract",
state = "VA",
county = "Goochland",
variables = c(popululation = "B02001_001"),
survey = "acs5",
geometry=TRUE,
year = Year) 

plot(Goochland_VA_population_2020[,"estimate"])
```
```{r}
library(tidyverse)
library(tidycensus)
Goochland_VA_unemployment_2020 <- get_acs(geography = "tract",
state = "VA",
county = "Goochland",
variables = c(unemployment = "S2301_C04_001"),
survey = "acs5",
geometry=TRUE,
year = Year) 

plot(Goochland_VA_unemployment_2020[,"estimate"])
```
```{r}
library(tidyverse)
library(tidycensus)
Goochland_VA_med.income_2020 <- get_acs(geography = "tract",
state = "VA",
county = "Goochland",
variables = c(median.household.income = "B19013_001"),
survey = "acs5",
geometry=TRUE,
year = Year) 

plot(Goochland_VA_med.income_2020[,"estimate"])
```


```{r}
library(tidyverse)
library(tidycensus)
edu.vars <- c(below_high = "S1501_C01_060",
              high_grad = "S1501_C01_061",
              some_col = "S1501_C01_062",
              bach = "S1501_C01_063",
              pro_grad = "S1501_C01_064")
Goochland_VA_education_attainment_2020 <- get_acs(geography = "county",
state = "VA",
county = "Goochland",
variables = c(education_attainment = edu.vars),
survey = "acs5",
geometry=TRUE,
year = Year) 

Goochland_VA_education_attainment_2020 %>% ggplot(aes(x = names(edu.vars), y = estimate, fill = names(edu.vars))) +
  geom_col() + theme(legend.position = "none") 
#will finish later must reorder.
```

```{r}
library(tidyverse)
library(tidycensus)
ocu.vars <- c(total = "B24011_001",
              "Management, business, science, and arts occupations" = "B24011_002",
              "Management, business, and financial occupations" = "B24011_003",
              "Management occupations" = "B24011_004",
              "Business and financial operations occupations" = "B24011_005",
              "Computer, engineering, and science occupations" = "B24011_006",
              "Computer and mathematical occupations" = "B24011_007",
              "Architecture and engineering occupations" = "B24011_008",
              "Life, physical, and social science occupations" = "B24011_009",
              "Education, legal, community service, arts, and media occupations" = "B24011_010",
              "Community and social service occupations" = "B24011_011",
              "Legal occupations" = "B24011_012",
              "Educational instruction, and library occupations" = "B24011_013",
              "Arts, design, entertainment, sports, and media occupations" = "B24011_014",
              "Healthcare practitioners and technical occupations" = "B24011_015",
              "Health diagnosing and treating practitioners and other technical occupations" = "B24011_016",
              "Health technologists and technicians" = "B24011_017",
              "Service occupations" = "B24011_018",
              "Healthcare support occupations" = "B24011_019",
              "Protective service occupations" = "B24011_020",
              "Firefighting and prevention, and other protective service workers including supervisors" = "B24011_021",
              "Law enforcement workers including supervisors" = "B24011_022",
              "Food preparation and serving related occupations" = "B24011_023",
              "Building and grounds cleaning and maintenance occupations" = "B24011_024",
              "Personal care and service occupations" = "B24011_025",
              "Sales and office occupations" = "B24011_026",
              "Sales and related occupations" = "B24011_027",
              "Office and administrative support occupations" = "B24011_028",
              "Natural resources, construction, and maintenance occupations" = "B24011_029",
              "Farming, fishing, and forestry occupations" = "B24011_030",
              "Construction and extraction occupations" = "B24011_031",
              "Installation, maintenance, and repair occupations" = "B24011_032",
              "Production, transportation, and material moving occupations" = "B24011_033",
              "Production occupations" = "B24011_034",
              "Transportation occupations" = "B24011_035",
              "Material moving occupations" = "B24011_036")
Goochland_VA_ocupation_2020 <- get_acs(geography = "county",
state = "VA",
county = "Goochland",
variables = ocu.vars,
survey = "acs5",
geometry=TRUE,
year = Year) 

sub.goochland <- Goochland_VA_ocupation_2020 %>% select(variable, estimate)
ggplot(sub.goochland, aes(x = variable, y = estimate, fill = variable) )+ geom_bar(stat = "identity") + coord_flip() + theme(legend.position = "none") # + labs()...

```