---
title: "ACS_visuals"
author: "JAM"
date: '2022-06-23'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tigris)
library(dplyr)
library(leaflet)
library(tidycensus)
library(tidyverse)
library(dplyr)
library(stringr)
library(tigris)
library(ggplot2)
library(viridis)
library(readxl)
library(gridExtra)
library(RColorBrewer)
library(ggpubr)
options(scipen=999)
```

```{r reading in data}
parcel2012 <- read_xlsx(paste0(getwd(), "/Tax_Par_2012.xlsx"))
parcel2021 <- read_xlsx(paste0(getwd(), "/Tax_Par_2021.xlsx"))
```

```{r}

possibleLables <- c("Single Family Suburban" = 2,
                    "Multi Family" = 3, 
                    "Commerical/Industrial" = 4,
                    "Ag/Undeveloped (20-99 Acres)" = 5, 
                    "Ag/Undeveloped (100+ Acres)" = 6,
                    "Federal Govt." = 71, 
                    "State Govt." = 72,
                    "Local Govt." = 74,
                    "Religious" = 76,
                    "Charitable" = 77,
                    "Educational" = 78,
                    "Other Exempt" = 79)


# 2012 data
parcel12.df <- parcel2012 %>%
  select(GPIN, MLUSE, Area_ACRE) %>%
  group_by(MLUSE) %>%
  arrange(MLUSE)

count12 <-parcel12.df %>%
  arrange(MLUSE, Area_ACRE) %>%
  count(MLUSE)

avgAcre12.df <- parcel12.df %>% 
  group_by(MLUSE) %>%
  summarize(totalAcre = sum(Area_ACRE)) %>%
  mutate(countUse = count12$n, averageAcre = totalAcre)
avgAcre12.df <- rbind(avgAcre12.df, c(3, 0, 0, 0))

avgAcre12.df <- na.omit(avgAcre12.df) %>% arrange(MLUSE) %>% mutate(MLUSE = names(possibleLables))

# 2021 data
parcel21.df <- parcel2021 %>%
  select(GPIN, MLUSE, Area_ACRE) %>%
  group_by(MLUSE) %>%
  arrange(MLUSE)

count21 <-parcel21.df %>%
  arrange(MLUSE, Area_ACRE) %>%
  count(MLUSE)

avgAcre21.df <- parcel21.df %>% 
  group_by(MLUSE) %>%
  summarize(totalAcre = sum(Area_ACRE)) %>%
  mutate(countUse = count21$n, averageAcre = totalAcre)

avgAcre21.df <- na.omit(avgAcre21.df) %>% mutate(MLUSE = names(possibleLables))




p12 <- ggplot(avgAcre12.df, aes(x = MLUSE, y = totalAcre, fill = MLUSE)) + 
  geom_bar(stat = "identity") + 
  scale_fill_viridis_d() + 
  coord_flip() + 
  scale_y_reverse() + 
  labs(title = "Acres per Land use (2012)", x = "", y = "Acres", fill = "Land Use") + 
  geom_text(aes(label = round(totalAcre,2)), hjust = 1.05) +
  theme(plot.title = element_text(hjust = 1), legend.position="none") + 
  scale_x_discrete(position = "top")+
  ylim(66000, 0)
  

p21 <- ggplot(avgAcre21.df, aes(x = MLUSE, y = totalAcre, fill = MLUSE)) + 
  geom_bar(stat = "identity") + 
  scale_fill_viridis_d() + 
  coord_flip() + 
  theme(legend.position = "none", axis.text.y = element_blank()) + 
  labs(title = "Acres per Land use (2021)", x = "", y = "Acres", caption = "Source: Administrative Data from Powhatan County") +
  geom_text(aes(label = round(totalAcre,2)), hjust = -.05)+
  ylim(0, 66000)

ggarrange(p12, p21, ncol=2, common.legend=TRUE, legend="bottom", labels=NULL)

grid.arrange(p12, p21, ncol=2, top = "Total Acres by land use (2012 vs. 2021)")

```

```{r making the pie charts}
mluse12.tbl <- table(parcel2012$MLUSE)[1:12]

pie12.df <- parcel2012 %>% 
  select(GPIN, MLUSE, Area_ACRE) %>% 
  group_by(MLUSE) %>% 
  arrange(MLUSE, Area_ACRE) %>%
  summarize(totalAcres = sum(Area_ACRE)) %>%
  mutate(MLUSE = factor(MLUSE, levels = MLUSE), totalAcres = totalAcres / mluse12.tbl)

mluse21.tbl <- table(parcel2021$MLUSE)
pie21.df <- parcel2021 %>% 
  select(MLUSE, Area_ACRE) %>% 
  group_by(MLUSE) %>% 
  summarize(totalAcres = sum(Area_ACRE)) %>%
  mutate(MLUSE = factor(MLUSE, levels = MLUSE))
```

```{r}

labels21 <- c("Single Family Suburban", "Multi Family", "Commercial/Industries", "Ag/Undeveloped (20-99 Acres)", "Ag/Undeveloped (100+ Acres)", "Federal Govt.", "State Govt.", "Local Govt.", "Religious", "Charitable", "Educational", "Other Exempt", "NA")

labels12 <- c("Single Family Suburban", "Commercial/Industrial", "Ag/Undeveloped (20-99 Acres)", "Ag/Undeveloped (100+ Acres)", "Federal Govt.", "State Govt.", "Local Govt.", "Religious", "Charitable", "Educational", "Other Exempt")



pie12 <- ggplot(pie12.df, aes(x ="", y = totalAcres, fill = MLUSE)) + 
  geom_bar(stat='identity') + 
  coord_polar("y", start = 0) + 
  labs(title = "Acerage of all Land Uses in Powhatan (2012)", fill = "", caption = "Source: Administrative Data from Powhatan County") + 
  theme_void() + 
  scale_fill_viridis_d(labels = labels12)


pie21 <- ggplot(pie21.df, aes(x ="", y = totalAcres, fill = MLUSE)) + 
  geom_bar(stat='identity') + 
  coord_polar("y", start = 0) + 
  labs(title = "Acerage of all Land Uses in Powhatan (2021)", fill = "", caption = "Source: Administrative Data from Powhatan County") + 
  theme_void() + 
  scale_fill_viridis_d(labels = labels21)

grid.arrange(pie12, pie21, ncol=2)
```

```{r Looking at ratios}
building12.df <- parcel2012 %>%
  filter(!(is.na(MCLASS))) %>%
  select(GPIN, MCLASS, MLUSE, MIMPRV, MTOTPR) %>%
  arrange(GPIN) %>%
  mutate(buildRatio = MIMPRV / MTOTPR)

hist(building12.df$buildRatio)

building21.df <- parcel2021 %>%
  filter(GPIN %in% building12.df$GPIN) %>%
  select(GPIN, MCLASS, MLUSE, MIMPRV, MTOTPR) %>%
  arrange(GPIN) %>%
  mutate(buildRatio = MIMPRV / MTOTPR)




```
