---
title: "ACS_visuals"
author: "JAM"
date: '2022-06-23'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tigris)
library(dplyr)
library(leaflet)
library(tidycensus)
library(tidyverse)
library(dplyr)
library(stringr)
library(tigris)
library(ggplot2)
library(viridis)
library(RColorBrewer)
options(scipen=999)
```


```{r parameters}
county = "Goochland"
year = 2020
fileName <- paste("/csv_data/ACS", year, county, ".rData", sep="")
```

```{r importing data}
setwd("C:/Users/malla/OneDrive/Desktop/DSPG/2022_DSPG_landuse")
load(paste0(getwd(), fileName))
```


```{r Household Size}

size.df <- data.frame(persons = houseSize$variables, percent = round(houseSize$estimate, 4) * 100)[-1,]
size.df$persons <- factor(size.df$persons, levels = c("onePerson", "twoPerson", "threePerson", "fourPlus"))

ggplot(size.df, aes(x = "", y = percent, fill = persons)) + 
  geom_col() + 
  coord_polar("y", start=0) + 
  geom_text(aes(label = percent), position = position_stack(vjust = 0.5)) + 
  theme(legend.text = element_text(size = 20)) + 
  theme_void() + 
  labs(title = "Proportion of persons living in households") + 
  scale_fill_discrete(name = "House size", labels = c("One person", "Two persons", "Three persons", "4+"))

```
```{r education}
edu_age.df <- data.frame(names = education_age$variable, values = education_age$estimate)[5:11,]
edu_age.df$names <- factor(edu_age.df$names, levels = edu_age.df$names)
ggplot(edu_age.df, aes(x = names, y = values, fill = names)) + geom_bar(stat = "identity") + theme(legend.position = "none") +labs(title = "Proportion of Population's Educational Attainment over the age of 25", x = "Highest Education", y = "percent of Population", caption = "Source: ACS5 2016-2020") +geom_text(aes(label = values), position = position_stack(vjust = 0.5)) + scale_x_discrete(labels = c("Below 9th", "9th Through 12th", "Highschool", "Some college", "Associates'", "Bachelor's", "Graduate"))
```

```{r Educational attainment} 

#fix red line value for goochland

edu_earn.df <- data.frame(name = education_earn$variable, values = education_earn$estimate)
edu_earn.df$name <- factor(edu_earn.df$name, levels = edu_earn.df$name)

ggplot(edu_earn.df, aes(x = name, y = values)) + 
  geom_bar(stat = "identity", mapping=(aes(fill = name))) + 
  geom_hline(yintercept = 52000, size = 2, color = "red") + 
  theme(legend.position = "none") + 
  labs(title = "Median Earnings by Educational Attainment over the age of 25", x = "Highest Education", y = "Median Earnings", caption = "Source: ACS5 2016-2020") + 
  geom_text(aes(label = values), position = position_stack(vjust = 0.5)) +
  scale_x_discrete(labels = c("Below\nhighschool", "Highschool\ngraduate", "Some college/\nAssociates'", "Bachelor's", "Graduate")) + 
  scale_y_continuous(breaks=c(0, 20000, 40000, 52000, 60000))
```


```{r Transportation}
trans.df <- data.frame(name = transportation$travel_type, value = transportation$estimate)
ggplot(trans.df, aes(x = "", y= value, fill= name)) +geom_col(color = "black") + coord_polar("y", start = 0) +
  geom_label(aes(label = round(value, 2)),
             position = position_stack(vjust = 0.5),
             show.legend = FALSE) + labs(title = "Means of Transportation to Work", x = "", y= "", caption = "ACS5 2016-2020" )
```

```{r median income}
plot(income[,"median"])
ggplot(income, aes(fill = median))+ geom_sf()+ scale_fill_distiller(palette="Reds", direction=1)+ labs(title="Median Income by Census Tract", caption="Source: ACS5 2016-2020", fill="Income") 
```

```{r median income}
pal <- colorNumeric(palette="viridis",1:6, domain=income$median)

leaflet() %>%
  addProviderTiles(providers$OpenStreetMap) %>%
  addPolygons(data=income, fillOpacity = 0.7, label=~median, color=~pal(median)) %>%
  addLegend(position="bottomleft", pal=pal, values=income$median, title= "Median Income",labFormat = labelFormat(transform = function(x) sort(x, decreasing = TRUE)))
```

```{r age distributions}
age.df <- data.frame(name = population$variable, value = population$estimate) [2:19,]
ages <- age.df$value
age.df$name<-factor(age.df$name, levels = age.df$name)
newcat <-c("9 and below", "10 to 19", "20 to 29", "30 to 39", "40 to 49", "50 to 59", "60 to 69", "70 to 79", "80 and above")
combined <- c(ages[1] + ages[2], 
              ages[3] + ages[4],
              ages[5] + ages[6], 
              ages[7] + ages[8],
              ages[9] + ages[10], 
              ages[11] + ages[12],
              ages[13] + ages[14], 
              ages[15] + ages[16],
              ages[17] + ages[18])
new.age.df <- data.frame(name = newcat, value = combined)
new.age.df$name<-factor(new.age.df$name, levels = new.age.df$name)



ggplot(new.age.df, aes(x=name , y=value, fill=new.age.df$name))+
  geom_bar(stat="identity") + 
  coord_flip() + 
  scale_fill_brewer(palette = "Set3") + 
  theme_light() + 
  theme(legend.position="none") + 
  labs(title="Proportion of Age Groups", y= "Proportion of Population", x= "Age Groups", caption="Source: ACS5 2016-2020")

# Want to use Set3 for discrete palettes
```


```{r population over time}
file <- paste("/csv_data/ACS", 2020, county, ".rData", sep="")
load(paste0(getwd(), file))
pop20 <- population$estimate[1]
file <- paste("/csv_data/ACS", 2019, county, ".rData", sep="")
load(paste0(getwd(), file))
pop19 <- population$estimate[1]
file <- paste("/csv_data/ACS", 2018, county, ".rData", sep="")
load(paste0(getwd(), file))
pop18 <- population$estimate[1]
file <- paste("/csv_data/ACS", 2017, county, ".rData", sep="")
load(paste0(getwd(), file))
pop17 <- population$estimate[1]
file <- paste("/csv_data/ACS", 2016, county, ".rData", sep="")
load(paste0(getwd(), file))
pop16 <- population$estimate[1]

pop_time.df <- data.frame(year = c(2016, 2017, 2018, 2019, 2020), values = c(pop16, pop17, pop18, pop19, pop20))


ggplot(pop_time.df, aes(x = year, y = values)) + geom_line(color = "DarkGreen") + ylim(20000, 30000) + labs(title = "Change in Population over Time", y = "Population", x = "Year", caption = "Source: ACS5 2011-2020")
# This doesn't really represent much
```

```{r industry}
ind.df <- data.frame(name = industry$variable, value = industry$estimate)

ggplot(ind.df, aes(x = reorder(name, -value), y = value)) + 
  geom_bar(stat = "identity", fill = c(3, rep(2, 12)), color = "black") + 
  coord_flip() + 
  labs(title = "Proportion of Population in Industries", x = "Proportion of Population", y = "Industry", caption = acs_Caption)
```




