---
title: "ParcelPlotting"
author: "JAM"
date: '2022-07-11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(RColorBrewer)
library(traveltime)
library(tidyverse)
library(tidycensus)
library(sf)
library(osmdata)
library(leaflet)
library(sp)
library(purrr)
library(mapview)
library(osrm)
library(rmapzen)
library(rgdal)
library(ggplot2)
library(scales)
library(nycflights13)
library(readxl)
library(rgdal)
```


```{r GOOCHLAND PLOTTING}
Gooch2018 <- read_sf("C:/Users/malla/OneDrive/Desktop/DSPG/2022_DSPG_landuse/Review/John/Goochland_Parcel_Data/Goochland_Original_Data_FIN/Gooch2018FIN.shp")
Gooch2019 <- read_sf("C:/Users/malla/OneDrive/Desktop/DSPG/2022_DSPG_landuse/Review/John/Goochland_Parcel_Data/Goochland_Original_Data_FIN/Gooch2019FIN.shp")
Gooch2020 <- read_sf("C:/Users/malla/OneDrive/Desktop/DSPG/2022_DSPG_landuse/Review/John/Goochland_Parcel_Data/Goochland_Original_Data_FIN/Gooch2020FIN.shp")
Gooch2021 <- read_sf("C:/Users/malla/OneDrive/Desktop/DSPG/2022_DSPG_landuse/Review/John/Goochland_Parcel_Data/Goochland_Original_Data_FIN/Gooch2021FIN.shp")

LUC_values <- c("Single Family Residential Urban", 
                "Single Family Residential Suburban", 
                "Multi-Family Residential", 
                "Commerical / Industrial", 
                "Agricultural / Undeveloped (20-99 Acres)", 
                "Agricultural / Undeveloped (100+ Acres)", 
                "Other", 
                "Undefined")
LUC_values <- factor(LUC_values, levels = LUC_values)

mypalette <- colorBin(palette = "Paired", as.numeric(LUC_values))
colors <- mypalette(unclass(LUC_values))





### 2018 ==========================================================================

code1.18 <- Gooch2018 %>% filter(LUC_FIN == "Single Family Residential Urban")
code2.18 <- Gooch2018 %>% filter(LUC_FIN == "Single Family Residential Suburban")
code3.18 <- Gooch2018 %>% filter(LUC_FIN == "Multi-Family Residential")
code4.18 <- Gooch2018 %>% filter(LUC_FIN == "Commerical / Industrial")
code5.18 <- Gooch2018 %>% filter(LUC_FIN == "Agricultural / Undeveloped (20-99 Acres)")
code6.18 <- Gooch2018 %>% filter(LUC_FIN == "Agricultural / Undeveloped (100+ Acres)")
code7.18 <- Gooch2018 %>% filter(LUC_FIN == "Other")
code0.18 <- Gooch2018 %>% filter(LUC_FIN == "Undefined")


gooch18 <- leaflet() %>%
  addTiles() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  
  addPolygons(data=code1.18$geometry, 
              fillColor = colors[1], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Single Family Urban") %>%
  addPolygons(data=code2.18$geometry, 
              fillColor = colors[2], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Single Family Suburban") %>%
  addPolygons(data=code3.18$geometry, 
              fillColor = colors[3], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Milti-Family Residential") %>%
  addPolygons(data=code4.18$geometry, 
              fillColor = colors[4], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Commercial & Industrial") %>%
  addPolygons(data=code5.18$geometry, 
              fillColor = colors[5], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Agriculture/Undeveloped (20-99 Acres)") %>%
  addPolygons(data=code6.18$geometry, 
              fillColor = colors[6], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Agriculture/Undeveloped (100+ Acres)") %>%
  addPolygons(data=code7.18$geometry, 
              fillColor = colors[7], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Other") %>%
  addPolygons(data=code0.18$geometry, 
              fillColor = colors[8], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Unknown") %>%
  addLayersControl(
    overlayGroups = c("Single Family Urban", "Single Family Suburban", "Milti-Family Residential", "Commercial & Industrial", "Agriculture/Undeveloped (20-99 Acres)", "Agriculture/Undeveloped (100+ Acres)", "Other", "Unknown"),
    position = "bottomleft",
    options = layersControlOptions(collapsed = FALSE)
  )



### 2019 ==========================================================================

code1.19 <- Gooch2019 %>% filter(LUC_FIN == "Single Family Residential Urban")
code2.19 <- Gooch2019 %>% filter(LUC_FIN == "Single Family Residential Suburban")
code3.19 <- Gooch2019 %>% filter(LUC_FIN == "Multi-Family Residential")
code4.19 <- Gooch2019 %>% filter(LUC_FIN == "Commerical / Industrial")
code5.19 <- Gooch2019 %>% filter(LUC_FIN == "Agricultural / Undeveloped (20-99 Acres)")
code6.19 <- Gooch2019 %>% filter(LUC_FIN == "Agricultural / Undeveloped (100+ Acres)")
code7.19 <- Gooch2019 %>% filter(LUC_FIN == "Other")
code0.19 <- Gooch2019 %>% filter(LUC_FIN == "Undefined")


gooch19 <- leaflet() %>%
  addTiles() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  
  addPolygons(data=code1.19$geometry, 
              fillColor = colors[1], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Single Family Urban") %>%
  addPolygons(data=code2.19$geometry, 
              fillColor = colors[2], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Single Family Suburban") %>%
  addPolygons(data=code3.19$geometry, 
              fillColor = colors[3], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Milti-Family Residential") %>%
  addPolygons(data=code4.19$geometry, 
              fillColor = colors[4], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Commercial & Industrial") %>%
  addPolygons(data=code5.19$geometry, 
              fillColor = colors[5], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Agriculture/Undeveloped (20-99 Acres)") %>%
  addPolygons(data=code6.19$geometry, 
              fillColor = colors[6], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Agriculture/Undeveloped (100+ Acres)") %>%
  addPolygons(data=code7.19$geometry, 
              fillColor = colors[7], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Other") %>%
  addPolygons(data=code0.19$geometry, 
              fillColor = colors[8], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Unknown") %>%
  addLayersControl(
    overlayGroups = c("Single Family Urban", "Single Family Suburban", "Milti-Family Residential", "Commercial & Industrial", "Agriculture/Undeveloped (20-99 Acres)", "Agriculture/Undeveloped (100+ Acres)", "Other", "Unknown"),
    position = "bottomleft",
    options = layersControlOptions(collapsed = FALSE)
  )

### 2020 ==========================================================================

code1.20 <- Gooch2020 %>% filter(LUC_FIN == "Single Family Residential Urban")
code2.20 <- Gooch2020 %>% filter(LUC_FIN == "Single Family Residential Suburban")
code3.20 <- Gooch2020 %>% filter(LUC_FIN == "Multi-Family Residential")
code4.20 <- Gooch2020 %>% filter(LUC_FIN == "Commerical / Industrial")
code5.20 <- Gooch2020 %>% filter(LUC_FIN == "Agricultural / Undeveloped (20-99 Acres)")
code6.20 <- Gooch2020 %>% filter(LUC_FIN == "Agricultural / Undeveloped (100+ Acres)")
code7.20 <- Gooch2020 %>% filter(LUC_FIN == "Other")
code0.20 <- Gooch2020 %>% filter(LUC_FIN == "Undefined")


gooch20 <- leaflet() %>%
  addTiles() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  
  addPolygons(data=code1.20$geometry, 
              fillColor = colors[1], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Single Family Urban") %>%
  addPolygons(data=code2.20$geometry, 
              fillColor = colors[2], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Single Family Suburban") %>%
  addPolygons(data=code3.20$geometry, 
              fillColor = colors[3], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Milti-Family Residential") %>%
  addPolygons(data=code4.20$geometry, 
              fillColor = colors[4], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Commercial & Industrial") %>%
  addPolygons(data=code5.20$geometry, 
              fillColor = colors[5], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Agriculture/Undeveloped (20-99 Acres)") %>%
  addPolygons(data=code6.20$geometry, 
              fillColor = colors[6], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Agriculture/Undeveloped (100+ Acres)") %>%
  addPolygons(data=code7.20$geometry, 
              fillColor = colors[7], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Other") %>%
  addPolygons(data=code0.20$geometry, 
              fillColor = colors[8], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Unknown") %>%
  addLayersControl(
    overlayGroups = c("Single Family Urban", "Single Family Suburban", "Milti-Family Residential", "Commercial & Industrial", "Agriculture/Undeveloped (20-99 Acres)", "Agriculture/Undeveloped (100+ Acres)", "Other", "Unknown"),
    position = "bottomleft",
    options = layersControlOptions(collapsed = FALSE)
  )


### 2021 ==========================================================================

code1.21 <- Gooch2021 %>% filter(LUC_FIN == "Single Family Residential Urban")
code2.21 <- Gooch2021 %>% filter(LUC_FIN == "Single Family Residential Suburban")
code3.21 <- Gooch2021 %>% filter(LUC_FIN == "Multi-Family Residential")
code4.21 <- Gooch2021 %>% filter(LUC_FIN == "Commerical / Industrial")
code5.21 <- Gooch2021 %>% filter(LUC_FIN == "Agricultural / Undeveloped (20-99 Acres)")
code6.21 <- Gooch2021 %>% filter(LUC_FIN == "Agricultural / Undeveloped (100+ Acres)")
code7.21 <- Gooch2021 %>% filter(LUC_FIN == "Other")
code0.21 <- Gooch2021 %>% filter(LUC_FIN == "Undefined")


gooch21 <- leaflet() %>%
  addTiles() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  
  addPolygons(data=code1.21$geometry, 
              fillColor = colors[1], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Single Family Urban") %>%
  addPolygons(data=code2.21$geometry, 
              fillColor = colors[2], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Single Family Suburban") %>%
  addPolygons(data=code3.21$geometry, 
              fillColor = colors[3], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Milti-Family Residential") %>%
  addPolygons(data=code4.21$geometry, 
              fillColor = colors[4], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Commercial & Industrial") %>%
  addPolygons(data=code5.21$geometry, 
              fillColor = colors[5], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Agriculture/Undeveloped (20-99 Acres)") %>%
  addPolygons(data=code6.21$geometry, 
              fillColor = colors[6], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Agriculture/Undeveloped (100+ Acres)") %>%
  addPolygons(data=code7.21$geometry, 
              fillColor = colors[7], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Other") %>%
  addPolygons(data=code0.21$geometry, 
              fillColor = colors[8], smoothFactor = 0.1, fillOpacity=1, stroke = FALSE,
              group = "Unknown") %>%
  addLayersControl(
    overlayGroups = c("Single Family Urban", "Single Family Suburban", "Milti-Family Residential", "Commercial & Industrial", "Agriculture/Undeveloped (20-99 Acres)", "Agriculture/Undeveloped (100+ Acres)", "Other", "Unknown"),
    position = "bottomleft",
    options = layersControlOptions(collapsed = FALSE)
  )
```


```{r}
gooch18
gooch19
gooch20
gooch21
```


