---
title: "Acs_plots_final"
author: "Christopher"
date: '2022-07-06'
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tigris)
library(dplyr)
library(leaflet)
library(tidycensus)
library(tidyverse)
library(dplyr)
library(stringr)
library(tigris)
library(ggplot2)
library(viridis)
library(RColorBrewer)
options(scipen=999)
```


```{r parameters}
county = "Goochland"
year = 2020
fileName <- paste("/ACS_rObjects/ACS", year, county, ".rData", sep="")
```

```{r importing data}
setwd("C:/Users/Christopher Vest/Documents/Land_use_project/Land_use")
load(paste0(getwd(), fileName))
```

```{r population}
age.df <- data.frame(name = population$variable, value = population$estimate) [2:19,]
ages <- age.df$value
age.df$name<-factor(age.df$name, levels = age.df$name)
newcat <-c("9 and below", "10 to 19", "20 to 29", "30 to 39", "40 to 49", "50 to 59", "60 to 69", "70 to 79", "80 and above")
combined <- c(ages[1] + ages[2], 
              ages[3] + ages[4],
              ages[5] + ages[6], 
              ages[7] + ages[8],
              ages[9] + ages[10], 
              ages[11] + ages[12],
              ages[13] + ages[14], 
              ages[15] + ages[16],
              ages[17] + ages[18])
new.age.df <- data.frame(name = newcat, value = combined)
new.age.df$name<-factor(new.age.df$name, levels = new.age.df$name)



ggplot(new.age.df, aes(x=name , y=value, fill=new.age.df$name))+
  geom_bar(stat="identity") + 
  coord_flip() + 
  scale_fill_viridis(discrete=TRUE) + 
  theme_light() + 
  theme(legend.position="none") + 
  labs(title="Proportion of Age Groups", y= "Proportion of Population", x= "Age Groups", caption="Source: ACS5 2016-2020")

# Want to use Set3 for discrete palettes
```

```{r industry}
ind.df <- data.frame(name = industry$variable, value = industry$estimate)

ggplot(ind.df, aes(x = reorder(name, -value), y = value, fill = value)) + 
  geom_bar(stat = "identity") + theme(legend.position = "none") +
  coord_flip() + scale_fill_viridis() + 
  labs(title = "Proportion of Population in Industries", y = "Proportion of Population", x = "Industry", caption = acs_Caption)
```

```{r median income}
plot(income)
ggplot(income, aes(x = median, y = NAME, fill = NAME))+ geom_bar(stat = "identity") + theme(legend.position = "none") + scale_fill_viridis(discrete=TRUE) + labs(title="Median Income by Census Tract", caption="Source: ACS5 2016-2020") 
```

```{r Educational attainment} 

#fix red line value for goochland

edu_earn.df <- data.frame(name = education_earn$variable, values = education_earn$estimate)
edu_earn.df$name <- factor(edu_earn.df$name, levels = edu_earn.df$name)

ggplot(edu_earn.df, aes(x = name, y = values)) + 
  geom_bar(stat = "identity", mapping=(aes(fill = name))) + 
  theme(legend.position = "none") + scale_fill_viridis(discrete=TRUE) +
  labs(title = "Median Earnings by Educational Attainment over the age of 25", x = "Highest Education", y = "Median Earnings", caption = "Source: ACS5 2016-2020") + 
  geom_text(aes(label = values), vjust = -0.25) +
  scale_x_discrete(labels = c("Below\nhighschool", "Highschool\ngraduate", "Some college/\nAssociates'", "Bachelor's", "Graduate")) + 
  scale_y_continuous(breaks=c(0, 20000, 40000, 52000, 60000))
```