---
title: "Relabelling Land Uses"
author: "JAM"
date: '2022-06-29'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(writexl)
library(foreign)
library(plyr)
library(dplyr)
```

```{r setting working directory and importing data}
setwd("C:/Users/malla/OneDrive/Desktop/DSPG/2022_DSPG_landuse")

# Importing the parcel data for both Powhatan and Goochland
taxPar_2021 <- read_xlsx("Powhatan_Parcel_Data/Tax_Par_2021.xlsx")
taxPar_2012 <- read_xlsx("Powhatan_Parcel_Data/Tax_Par_2012.xlsx")
parc_point_2012_2021 <- read.csv("Powhatan_Parcel_Data/Parc_point_2012_2021.csv")

goochland_2018 <- read.csv("Goochland_Parcel_Data/2018_goochland.csv")
goochland_2022 <- read.csv("Goochland_Parcel_Data/2022_goochland.csv")
goochland_parcellation <- read.csv("Goochland_Parcel_Data/Gooch_Parcellation_2018_2022.csv")

## Powhatan Parcels
pow_2012.dbf <- read.dbf("Powhatan_Parcel_Data/Powhatan_Reduced_Data/PowReduTaxParcels2012.dbf")
pow_2013.dbf <- read.dbf("Powhatan_Parcel_Data/Powhatan_Reduced_Data/PowReduTaxParcels2013.dbf")
pow_2014.dbf <- read.dbf("Powhatan_Parcel_Data/Powhatan_Reduced_Data/PowReduTaxParcels2014.dbf")
pow_2015.dbf <- read.dbf("Powhatan_Parcel_Data/Powhatan_Reduced_Data/PowReduTaxParcels2015.dbf")
pow_2016.dbf <- read.dbf("Powhatan_Parcel_Data/Powhatan_Reduced_Data/PowReduTaxParcels2016.dbf")
pow_2017.dbf <- read.dbf("Powhatan_Parcel_Data/Powhatan_Reduced_Data/PowReduTaxParcels2017.dbf")
pow_2018.dbf <- read.dbf("Powhatan_Parcel_Data/Powhatan_Reduced_Data/PowReduTaxParcels2018.dbf")
pow_2019.dbf <- read.dbf("Powhatan_Parcel_Data/Powhatan_Reduced_Data/PowReduTaxParcels2019.dbf")
pow_2020.dbf <- read.dbf("Powhatan_Parcel_Data/Powhatan_Reduced_Data/PowReduTaxParcels2020.dbf")
pow_2021.dbf <- read.dbf("Powhatan_Parcel_Data/Powhatan_Reduced_Data/PowReduTaxParcels2021.dbf")

## Powhatan Parcellation
pow_12_21.dbf <- read.dbf("Powhatan_Parcel_Data/Powhatan_Parcellation/Pow_12_21_all_parcellation.dbf")
pow_12_13.dbf <- read.dbf("Powhatan_Parcel_Data/Powhatan_Parcellation/Pow_13_12_parcellation.dbf")
pow_13_14.dbf <- read.dbf("Powhatan_Parcel_Data/Powhatan_Parcellation/Pow_14_13_parcellation.dbf")
pow_14_15.dbf <- read.dbf("Powhatan_Parcel_Data/Powhatan_Parcellation/Pow_15_14_parcellation.dbf")
pow_15_16.dbf <- read.dbf("Powhatan_Parcel_Data/Powhatan_Parcellation/Pow_16_15_parcellation.dbf")
pow_16_17.dbf <- read.dbf("Powhatan_Parcel_Data/Powhatan_Parcellation/Pow_17_16_parcellation.dbf")
pow_17_18.dbf <- read.dbf("Powhatan_Parcel_Data/Powhatan_Parcellation/Pow_18_17_parcellation.dbf")
pow_18_19.dbf <- read.dbf("Powhatan_Parcel_Data/Powhatan_Parcellation/Pow_19_18_parcellation.dbf")
pow_19_20.dbf <- read.dbf("Powhatan_Parcel_Data/Powhatan_Parcellation/Pow_20_19_parcellation.dbf")
pow_20_21.dbf <- read.dbf("Powhatan_Parcel_Data/Powhatan_Parcellation/Pow_21_20_parcellation.dbf")

## Goochland Parcels
gooch_2018.dbf <- read.dbf("Goochland_Parcel_Data/Goochland_Original_Data/Gooch_2018.dbf")
gooch_2019.dbf <- read.dbf("Goochland_Parcel_Data/Goochland_Original_Data/Gooch_2019.dbf")
gooch_2020.dbf <- read.dbf("Goochland_Parcel_Data/Goochland_Original_Data/Gooch_2020.dbf")
gooch_2021.dbf <- read.dbf("Goochland_Parcel_Data/Goochland_Original_Data/Gooch_2021.dbf")

## Goochland Parcellation
gooch_18_21.dbf <- read.dbf("Goochland_Parcel_Data/Goochland_Parcellation/Gooch_18_22_all_parcellation.dbf")
gooch_18_19.dbf <- read.dbf("Goochland_Parcel_Data/Goochland_Parcellation/Gooch_Parcellation_19_18.dbf")
gooch_20_19.dbf <- read.dbf("Goochland_Parcel_Data/Goochland_Parcellation/Gooch_Parcellation_20_19.dbf")
gooch_21_20.dbf <- read.dbf("Goochland_Parcel_Data/Goochland_Parcellation/Gooch_Parcellation_21_20.dbf")

# Master Codes
master_relabel <- read_excel("LUC_codes/LUC_codeToName.xlsx", sheet = "codeToName")
```

```{r Relabelling Powhatan (all parcels)}
# Going to be around 9 relabellings through this chunk of code.

# Declaring the land use variables
MLUSE21 <- taxPar_2021$MLUSE
MLUSE12 <- taxPar_2012$MLUSE
pow_relabel <- read_excel("LUC_codes/LUC_codeToName.xlsx", sheet = "Powhatan")

# Converting na's to 0's
MLUSE21[is.na(MLUSE21)] <- 0
MLUSE12[is.na(MLUSE12)] <- 0

# Replacing codes to LUC

# 2012
for(i in 1:length(MLUSE12)){
  MLUSE12[i] <- pow_relabel$pow_code[MLUSE12[i] == pow_relabel$pow_value]
  MLUSE12[i] <- master_relabel$code_name[MLUSE12[i] == master_relabel$code_value]
}
# 2021
for(i in 1:length(MLUSE21)){ 
  MLUSE21[i] <- pow_relabel$pow_code[MLUSE21[i] == pow_relabel$pow_value]
  MLUSE21[i] <- master_relabel$code_name[MLUSE21[i] == master_relabel$code_value]
}

# re assigning the data frame
taxPar_2012$MLUSE <- MLUSE12
taxPar_2021$MLUSE <- MLUSE21

```


```{r relabelling parc point}

MLUSE12 <- parc_point_2012_2021$MLUSE_12
MLUSE21 <- parc_point_2012_2021$MLUSE

MLUSE12[is.na(MLUSE12)] <- 0
MLUSE21[is.na(MLUSE21)] <- 0

for(i in 1:nrow(parc_point_2012_2021)){
  MLUSE12[i] <- pow_relabel$pow_code[MLUSE12[i] == pow_relabel$pow_value]
  MLUSE12[i] <- master_relabel$code_name[MLUSE12[i] == master_relabel$code_value]
  
  MLUSE21[i] <- pow_relabel$pow_code[MLUSE21[i] == pow_relabel$pow_value]
  MLUSE21[i] <- master_relabel$code_name[MLUSE21[i] == master_relabel$code_value]
}

parc_point_2012_2021$MLUSE_12 <- MLUSE12
parc_point_2012_2021$MLUSE <- MLUSE21

```

```{r relabelling Powhatan individual}

# for MLUSE new
pow_12_21_remap <- as.numeric(mapvalues(pow_12_21.dbf$MLUSE, pow_relabel$pow_value, pow_relabel$pow_code))
pow_12_21_remap[is.na(pow_12_21_remap)] <- 0
pow_12_21_remap <- mapvalues(pow_12_21_remap, master_relabel$code_value, master_relabel$code_name)

pow_12_13_remap <- as.numeric(mapvalues(pow_12_13.dbf$MLUSE, pow_relabel$pow_value, pow_relabel$pow_code))
pow_12_13_remap[is.na(pow_12_13_remap)] <- 0
pow_12_13_remap <- mapvalues(pow_12_13_remap, master_relabel$code_value, master_relabel$code_name)

pow_13_14_remap <- as.numeric(mapvalues(pow_13_14.dbf$MLUSE, pow_relabel$pow_value, pow_relabel$pow_code))
pow_13_14_remap[is.na(pow_13_14_remap)] <- 0
pow_13_14_remap <- mapvalues(pow_13_14_remap, master_relabel$code_value, master_relabel$code_name)

pow_14_15_remap <- as.numeric(mapvalues(pow_14_15.dbf$MLUSE, pow_relabel$pow_value, pow_relabel$pow_code))
pow_14_15_remap[is.na(pow_14_15_remap)] <- 0
pow_14_15_remap <- mapvalues(pow_14_15_remap, master_relabel$code_value, master_relabel$code_name)

pow_15_16_remap <- as.numeric(mapvalues(pow_15_16.dbf$MLUSE, pow_relabel$pow_value, pow_relabel$pow_code))
pow_15_16_remap[is.na(pow_15_16_remap)] <- 0
pow_15_16_remap <- mapvalues(pow_15_16_remap, master_relabel$code_value, master_relabel$code_name)

pow_16_17_remap <- as.numeric(mapvalues(pow_16_17.dbf$MLUSE, pow_relabel$pow_value, pow_relabel$pow_code))
pow_16_17_remap[is.na(pow_16_17_remap)] <- 0
pow_16_17_remap <- mapvalues(pow_16_17_remap, master_relabel$code_value, master_relabel$code_name)

pow_17_18_remap <- as.numeric(mapvalues(pow_17_18.dbf$MLUSE, pow_relabel$pow_value, pow_relabel$pow_code))
pow_17_18_remap[is.na(pow_17_18_remap)] <- 0
pow_17_18_remap <- mapvalues(pow_17_18_remap, master_relabel$code_value, master_relabel$code_name)

pow_18_19_remap <- as.numeric(mapvalues(pow_18_19.dbf$MLUSE, pow_relabel$pow_value, pow_relabel$pow_code))
pow_18_19_remap[is.na(pow_18_19_remap)] <- 0
pow_18_19_remap <- mapvalues(pow_18_19_remap, master_relabel$code_value, master_relabel$code_name)

pow_19_20_remap <- as.numeric(mapvalues(pow_19_20.dbf$MLUSE, pow_relabel$pow_value, pow_relabel$pow_code))
pow_19_20_remap[is.na(pow_19_20_remap)] <- 0
pow_19_20_remap <- mapvalues(pow_19_20_remap, master_relabel$code_value, master_relabel$code_name)

pow_20_21_remap <- as.numeric(mapvalues(pow_20_21.dbf$MLUSE, pow_relabel$pow_value, pow_relabel$pow_code))
pow_20_21_remap[is.na(pow_20_21_remap)] <- 0
pow_20_21_remap <- mapvalues(pow_20_21_remap, master_relabel$code_value, master_relabel$code_name)

# for MLUSE old
pow_12_21_remap1 <- as.numeric(mapvalues(pow_12_21.dbf$MLUSE_1, pow_relabel$pow_value, pow_relabel$pow_code))
pow_12_21_remap1[is.na(pow_12_21_remap1)] <- 0
pow_12_21_remap1 <- mapvalues(pow_12_21_remap1, master_relabel$code_value, master_relabel$code_name)

pow_12_13_remap1 <- as.numeric(mapvalues(pow_12_13.dbf$MLUSE_1, pow_relabel$pow_value, pow_relabel$pow_code))
pow_12_13_remap1[is.na(pow_12_13_remap1)] <- 0
pow_12_13_remap1 <- mapvalues(pow_12_13_remap1, master_relabel$code_value, master_relabel$code_name)

pow_13_14_remap1 <- as.numeric(mapvalues(pow_13_14.dbf$MLUSE_1, pow_relabel$pow_value, pow_relabel$pow_code))
pow_13_14_remap1[is.na(pow_13_14_remap1)] <- 0
pow_13_14_remap1 <- mapvalues(pow_13_14_remap1, master_relabel$code_value, master_relabel$code_name)

pow_14_15_remap1 <- as.numeric(mapvalues(pow_14_15.dbf$MLUSE_1, pow_relabel$pow_value, pow_relabel$pow_code))
pow_14_15_remap1[is.na(pow_14_15_remap1)] <- 0
pow_14_15_remap1 <- mapvalues(pow_14_15_remap1, master_relabel$code_value, master_relabel$code_name)

pow_15_16_remap1 <- as.numeric(mapvalues(pow_15_16.dbf$MLUSE_1, pow_relabel$pow_value, pow_relabel$pow_code))
pow_15_16_remap1[is.na(pow_15_16_remap1)] <- 0
pow_15_16_remap1 <- mapvalues(pow_15_16_remap1, master_relabel$code_value, master_relabel$code_name)

pow_16_17_remap1 <- as.numeric(mapvalues(pow_16_17.dbf$MLUSE_1, pow_relabel$pow_value, pow_relabel$pow_code))
pow_16_17_remap1[is.na(pow_16_17_remap1)] <- 0
pow_16_17_remap1 <- mapvalues(pow_16_17_remap1, master_relabel$code_value, master_relabel$code_name)

pow_17_18_remap1 <- as.numeric(mapvalues(pow_17_18.dbf$MLUSE_1, pow_relabel$pow_value, pow_relabel$pow_code))
pow_17_18_remap1[is.na(pow_17_18_remap1)] <- 0
pow_17_18_remap1 <- mapvalues(pow_17_18_remap1, master_relabel$code_value, master_relabel$code_name)

pow_18_19_remap1 <- as.numeric(mapvalues(pow_18_19.dbf$MLUSE_1, pow_relabel$pow_value, pow_relabel$pow_code))
pow_18_19_remap1[is.na(pow_18_19_remap1)] <- 0
pow_18_19_remap1 <- mapvalues(pow_18_19_remap1, master_relabel$code_value, master_relabel$code_name)

pow_19_20_remap1 <- as.numeric(mapvalues(pow_19_20.dbf$MLUSE_1, pow_relabel$pow_value, pow_relabel$pow_code))
pow_19_20_remap1[is.na(pow_19_20_remap1)] <- 0
pow_19_20_remap1 <- mapvalues(pow_19_20_remap1$MLUSE_1, master_relabel$code_value, master_relabel$code_name)

pow_20_21_remap1 <- as.numeric(mapvalues(pow_20_21.dbf$MLUSE_1, pow_relabel$pow_value, pow_relabel$pow_code))
pow_20_21_remap1[is.na(pow_20_21_remap1)] <- 0
pow_20_21_remap1 <- mapvalues(pow_20_21_remap1, master_relabel$code_value, master_relabel$code_name)

pow_12_21.dbf <- cbind(pow_12_21.dbf, MLUSE_relab = pow_12_21_remap, MLUSE_12_relab = pow_12_21_remap1)
pow_12_13.dbf <- cbind(pow_12_13.dbf, MLUSE_relab = pow_12_13_remap, MLUSE_12_relab = pow_12_13_remap1)
pow_13_14.dbf <- cbind(pow_13_14.dbf, MLUSE_relab = pow_13_14_remap, MLUSE_12_relab = pow_13_14_remap1)
pow_14_15.dbf <- cbind(pow_14_15.dbf, MLUSE_relab = pow_14_15_remap, MLUSE_12_relab = pow_14_15_remap1)
pow_15_16.dbf <- cbind(pow_15_16.dbf, MLUSE_relab = pow_15_16_remap, MLUSE_12_relab = pow_15_16_remap1)
pow_16_17.dbf <- cbind(pow_16_17.dbf, MLUSE_relab = pow_16_17_remap, MLUSE_12_relab = pow_16_17_remap1)
pow_17_18.dbf <- cbind(pow_17_18.dbf, MLUSE_relab = pow_17_18_remap, MLUSE_12_relab = pow_17_18_remap1)
pow_18_19.dbf <- cbind(pow_18_19.dbf, MLUSE_relab = pow_18_19_remap, MLUSE_12_relab = pow_18_19_remap1)
pow_19_20.dbf <- cbind(pow_19_20.dbf, MLUSE_relab = pow_19_20_remap, MLUSE_12_relab = pow_19_20_remap1)
pow_20_21.dbf <- cbind(pow_20_21.dbf, MLUSE_relab = pow_20_21_remap, MLUSE_12_relab = pow_20_21_remap1)


# Individual Parcel Data
pow_2012_remap <- as.numeric(mapvalues(pow_2012.dbf$MLUSE, pow_relabel$pow_value, pow_relabel$pow_code))
pow_2012_remap[is.na(pow_2012_remap)] <- 0
pow_2012_remap <- mapvalues(pow_2012_remap, master_relabel$code_value, master_relabel$code_name)

pow_2013_remap <- as.numeric(mapvalues(pow_2013.dbf$MLUSE, pow_relabel$pow_value, pow_relabel$pow_code))
pow_2013_remap[is.na(pow_2013_remap)] <- 0
pow_2013_remap <- mapvalues(pow_2013_remap, master_relabel$code_value, master_relabel$code_name)

pow_2014_remap <- as.numeric(mapvalues(pow_2014.dbf$MLUSE, pow_relabel$pow_value, pow_relabel$pow_code))
pow_2014_remap[is.na(pow_2014_remap)] <- 0
pow_2014_remap <- mapvalues(pow_2014_remap, master_relabel$code_value, master_relabel$code_name)

pow_2015_remap <- as.numeric(mapvalues(pow_2015.dbf$MLUSE, pow_relabel$pow_value, pow_relabel$pow_code))
pow_2015_remap[is.na(pow_2012_remap)] <- 0
pow_2015_remap <- mapvalues(pow_2015_remap, master_relabel$code_value, master_relabel$code_name)

pow_2016_remap <- as.numeric(mapvalues(pow_2016.dbf$MLUSE, pow_relabel$pow_value, pow_relabel$pow_code))
pow_2016_remap[is.na(pow_2016_remap)] <- 0
pow_2016_remap <- mapvalues(pow_2016_remap, master_relabel$code_value, master_relabel$code_name)

pow_2017_remap <- as.numeric(mapvalues(pow_2017.dbf$MLUSE, pow_relabel$pow_value, pow_relabel$pow_code))
pow_2017_remap[is.na(pow_2017_remap)] <- 0
pow_2017_remap <- mapvalues(pow_2017_remap, master_relabel$code_value, master_relabel$code_name)

pow_2018_remap <- as.numeric(mapvalues(pow_2018.dbf$MLUSE, pow_relabel$pow_value, pow_relabel$pow_code))
pow_2018_remap[is.na(pow_2018_remap)] <- 0
pow_2018_remap <- mapvalues(pow_2018_remap, master_relabel$code_value, master_relabel$code_name)

pow_2019_remap <- as.numeric(mapvalues(pow_2019.dbf$MLUSE, pow_relabel$pow_value, pow_relabel$pow_code))
pow_2019_remap[is.na(pow_2019_remap)] <- 0
pow_2019_remap <- mapvalues(pow_2019_remap, master_relabel$code_value, master_relabel$code_name)

pow_2020_remap <- as.numeric(mapvalues(pow_2020.dbf$MLUSE, pow_relabel$pow_value, pow_relabel$pow_code))
pow_2020_remap[is.na(pow_2020_remap)] <- 0
pow_2020_remap <- mapvalues(pow_2020_remap, master_relabel$code_value, master_relabel$code_name)

pow_2021_remap <- mapvalues(pow_2021.dbf$MLUSE, pow_relabel$pow_value, pow_relabel$pow_code)
pow_2021_remap[is.na(pow_2021_remap)] <- 0
pow_2021_remap <- mapvalues(pow_2021_remap, master_relabel$code_value, master_relabel$code_name)

```


```{r Goochland 2018 relabeling LUC}
MLUSE <- goochland_2018$LUC
gooch_2018_relabel <- read_excel("LUC_codes/LUC_codeToName.xlsx", sheet = "Goochland 2018")

# Converting na's to 0's
MLUSE[is.na(MLUSE)] <- 0

# There's a small problem with a few labelled uses
gooch_2018_relabel$gooch_value[20] <- "3 Multi-Family "
gooch_2018_relabel$gooch_value[15] <- "19 TAXED-SCC\nTAXED BY SCC"
gooch_2018_relabel$gooch_value[1] <- "17 NOT TAXABLE "
gooch_2018_relabel[28,] <- data.frame(gooch_value = "", gooch_code = 7)


# Replacing Powhatan's LUC codes to right codes
for(i in 1:length(MLUSE)){
  MLUSE[i] <- gooch_2018_relabel$gooch_code[MLUSE[i] == gooch_2018_relabel$gooch_value]
  MLUSE[i] <- master_relabel$code_name[MLUSE[i] == master_relabel$code_value]
}
goochland_2018$LUC <- MLUSE
```


```{r Goochland 2022}
MLUSE <- goochland_2022$LUC

gooch_2022_relabel <- read_excel("LUC_codes/LUC_codeToName.xlsx", sheet = "Goochland 2022")

# Converting na's to 0's
MLUSE[is.na(MLUSE)] <- 0

for(i in 1:length(MLUSE)){
  MLUSE[i] <- gooch_2022_relabel$gooch_code[MLUSE[i] == gooch_2022_relabel$gooch_value]
  MLUSE[i] <- master_relabel$code_name[MLUSE[i] == master_relabel$code_value]
}
goochland_2022$LUC <- MLUSE
```


```{r Goochland Parcellation}
MLUSE18 <- goochland_parcellation$LandUseCod2018
MLUSE22 <- goochland_parcellation$LUC_2022

gooch_2022_relabel <- read_excel("LUC_codes/LUC_codeToName.xlsx", sheet = "Goochland Parcellation 2022")
gooch_2018_relabel <- read_excel("LUC_codes/LUC_codeToName.xlsx", sheet = "Goochland Parcellation 2018")


# Converting na's to 0's
MLUSE18[is.na(MLUSE18)] <- 0
MLUSE22[is.na(MLUSE22)] <- 0

for(i in 1:nrow(goochland_parcellation)){
  # 2018
  MLUSE18[i] <- gooch_2018_relabel$gooch_code[MLUSE18[i] == gooch_2018_relabel$gooch_value]
  MLUSE18[i] <- master_relabel$code_name[MLUSE18[i] == master_relabel$code_value]

  # 2022
  MLUSE22[i] <- gooch_2022_relabel$gooch_code[MLUSE22[i] == gooch_2022_relabel$gooch_value]
  MLUSE22[i] <- master_relabel$code_name[MLUSE22[i] == master_relabel$code_value]
}

goochland_parcellation$LUC_2022 <- MLUSE22
goochland_parcellation$LandUseCod2018 <- MLUSE18

```


```{r Saving cleaned data}
# Writing Powhatan Data
write_xlsx(taxPar_2012, "LUC_codes/Cleaned_Parcel_Data/Tax_Par_2012CLEANED.xlsx")

write_xlsx(taxPar_2021, "LUC_codes/Cleaned_Parcel_Data/Tax_Par_2021CLEANED.xlsx")

write_csv(parc_point_2012_2021, "LUC_codes/Cleaned_Parcel_Data/Parc_point_2012_2021CLEANED.csv")


# Writing Goochland Data

write_csv(goochland_parcellation, "LUC_codes/Cleaned_Parcel_Data/Gooch_Parcellation_2018_2022CLEANED.csv")

write_csv(goochland_2018, "LUC_codes/Cleaned_Parcel_Data/2018_goochlandCLEANED.csv")

write_csv(goochland_2022, "LUC_codes/Cleaned_Parcel_Data/2022_goochlandCLEANED.csv")
```





