---
title: "Croplayer_gram"
author: "Christopher"
date: '2022-07-11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(ggplot2)
library(viridis)
library(readxl)
library(plotly)

```

```{r}
croplayer1 <- read_excel("C:/Users/Christopher Vest/Documents/Land_use_project/2022_DSPG_Landuse/Review/Christopher/Croplayer/Ag_Analysis_Gooch_Powhatan.xlsx", sheet = "2021")
croplayer2 <- read_excel("C:/Users/Christopher Vest/Documents/Land_use_project/2022_DSPG_Landuse/Review/Christopher/Croplayer/Ag_Analysis_Gooch_Powhatan.xlsx", sheet = "2012")
```
```{r Powhatan 2021}
p_21 <- ggplot(croplayer1, aes(x = reorder(`Powhatan Combined`, `Area Acre...2`), y = `Area Acre...2`, fill = `Area Acre...2`)) + geom_bar(stat = "identity", aes(text = paste0(`Powhatan Combined`, "\n", "Total Acres: ", round(`Area Acre...2`, 0)))) + coord_flip() + theme(legend.position = "none") +     scale_fill_viridis() + labs( title = "Total Acreage by Land type", x = "Acreage", y = "Land type")
ggplotly(p_21, tooltip = c("text")) %>%
  layout(annotations = list(x = 1, y = -0.1, text = "Source: NASS", showarrow = F, xref='paper', yref='paper', 
      xanchor='right', yanchor='auto'))
```
```{r Goochland 2021}
g_21 <- ggplot(croplayer1, aes(x = reorder(`Goochland Combined`, `Area Acre...4`), y = `Area Acre...4`, fill = `Area Acre...4`)) + geom_bar(stat = "identity", aes(text = paste0(`Goochland Combined`, "\n", "Total Acres: ", round(`Area Acre...4`, 0)))) + coord_flip() + theme(legend.position = "none") +     scale_fill_viridis() + labs( title = "Total Acreage by Land type", x = "Acreage", y = "Land type")
ggplotly(g_21, tooltip = c("text")) %>%
  layout(annotations = list(x = 1, y = -0.1, text = "Source: NASS", showarrow = F, xref='paper', yref='paper', 
      xanchor='right', yanchor='auto'))
```

```{r Powhatan 2012}
p_12 <- ggplot(croplayer2, aes(x = reorder(`Powhatan Combined`, `Area_acre...3`), y = `Area_acre...3`, fill = `Area_acre...3`)) + geom_bar(stat = "identity", aes(text = paste0(`Powhatan Combined`, "\n", "Total Acres: ", round(`Area_acre...3`, 0)))) + coord_flip() + theme(legend.position = "none") +     scale_fill_viridis() + labs( title = "Total Acreage by Land type", x = "Acreage", y = "Land type")
ggplotly(p_12, tooltip = c("text")) %>%
  layout(annotations = list(x = 1, y = -0.1, text = "Source: NASS", showarrow = F, xref='paper', yref='paper', 
      xanchor='right', yanchor='auto'))
```
```{r Goochland 2012}
g_12 <- ggplot(croplayer2, aes(x = reorder(`Goochland Combined`, `Area_acre...5`), y = `Area_acre...5`, fill = `Area_acre...5`)) + geom_bar(stat = "identity", aes(text = paste0(`Goochland Combined`, "\n", "Total Acres: ", round(`Area Acre...5`, 0)))) + coord_flip() + theme(legend.position = "none") +     scale_fill_viridis() + labs( title = "Total Acreage by Land type", x = "Acreage", y = "Land type")
ggplotly(p_12, tooltip = c("text")) %>%
  layout(annotations = list(x = 1, y = -0.1, text = "Source: NASS", showarrow = F, xref='paper', yref='paper', 
      xanchor='right', yanchor='auto'))
```
