---
title: "Croplayer_gram"
author: "Christopher"
date: '2022-07-11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(ggplot2)
library(viridis)
library(readxl)
library(plotly)
library(tidyverse)

options(scipen = 999)   
```

```{r}

croplayer1 <- read_excel("C:/Users/Christopher Vest/Documents/Land_use_project/2022_DSPG_Landuse/Review/Christopher/Croplayer/Ag_Analysis.xlsx")
library(dplyr)
data_round <- croplayer1 %>%                   # Using dplyr functions
  mutate_if(is.numeric,
            round,
            digits = 0)
write.csv(data_round, "C:/Users/Christopher Vest/Documents/Land_use_project/2022_DSPG_Landuse/Review/Christopher/Croplayer/ag_analysis.csv", row.names = FALSE)
croplayer1 <- read.csv("C:/Users/Christopher Vest/Documents/Land_use_project/2022_DSPG_Landuse/Review/Christopher/Croplayer/ag_analysis.csv")
```
```{r Powhatan 2021}
library(tidyverse)
library(viridis)

p_21 <- croplayer1 %>% # change county and year here
  filter(County == "Powhatan", Year==2021) %>%
  ggplot(aes(x = reorder(`Combined`, `Area.Acre`), y = `Area.Acre`, fill = `Area.Acre`)) + 
  geom_bar(stat = "identity", aes(text = paste0(`Combined`, "\n", "Total Acres: ", round(`Area.Acre`, 0)))) + 
  coord_flip() + 
  theme_light() +
  theme(axis.text.y = element_text(hjust=0)) +
  theme(legend.position = "none") + 
  scale_fill_viridis() + 
  labs( title = "Total Acreage by Land type", x = "Acreage", y = "Land type")
ggplotly(p_21, tooltip = c("text")) %>%
  layout(annotations = list(x = 1, y = -0.1, text = "Source: NASS", showarrow = F, xref='paper', yref='paper', 
      xanchor='right', yanchor='auto'))
```

```{r Goochland 2021}

g_21 <- croplayer1 %>% # change county and year here
  filter(County == "Goochland", Year==2021) %>%
ggplot(aes(x = reorder(`Combined`, `Area.Acre`), y = `Area.Acre`, fill = `Area.Acre`)) + 
  geom_bar(stat = "identity", aes(text = paste0(`Combined`, "\n", "Total Acres: ", round(`Area.Acre`, 0)))) + 
  coord_flip() +  
  theme_light() +
  theme(axis.text.y = element_text(hjust=0)) +
  theme(legend.position = "none") +     
  scale_fill_viridis() + 
  labs( title = "Total Acreage by Land type", x = "Acreage", y = "Land type")
ggplotly(g_21, tooltip = c("text")) %>%
  layout(annotations = list(x = 1, y = -0.1, text = "Source: NASS", showarrow = F, xref='paper', yref='paper', 
      xanchor='right', yanchor='auto'))
```




```{r Powhatan 2012}
p_12 <- croplayer1 %>% # change county and year here
  filter(County == "Powhatan", Year== 2012) %>%
  ggplot(aes(x = reorder(`Combined`, `Area.Acre`), y = `Area.Acre`, fill = `Area.Acre`)) + 
  geom_bar(stat = "identity", aes(text = paste0(`Combined`, "\n", "Total Acres: ", round(`Area.Acre`, 0)))) + 
  coord_flip() + 
  theme_light() +
  theme(axis.text.y = element_text(hjust=0)) +
  theme(legend.position = "none") + 
  scale_fill_viridis() + 
  labs( title = "Total Acreage by Land type", x = "Acreage", y = "Land type")
ggplotly(p_12, tooltip = c("text")) %>%
  layout(annotations = list(x = 1, y = -0.1, text = "Source: NASS", showarrow = F, xref='paper', yref='paper', 
      xanchor='right', yanchor='auto'))
```

```{r Goochland 2012}
g_12 <- croplayer1 %>% # change county and year here
  filter(County == "Goochland", Year== 2012) %>%
  ggplot(aes(x = reorder(`Combined`, `Area.Acre`), y = `Area.Acre`, fill = `Area.Acre`)) + 
  geom_bar(stat = "identity", aes(text = paste0(`Combined`, "\n", "Total Acres: ", round(`Area.Acre`, 0)))) + 
  coord_flip() + 
  theme_light() +
  theme(axis.text.y = element_text(hjust=0)) +
  theme(legend.position = "none") + 
  scale_fill_viridis() + 
  labs( title = "Total Acreage by Land type", x = "Acreage", y = "Land type")
ggplotly(g_12, tooltip = c("text")) %>%
  layout(annotations = list(x = 1, y = -0.1, text = "Source: NASS", showarrow = F, xref='paper', yref='paper', 
      xanchor='right', yanchor='auto'))
```
