---
title: "soil_quality"
author: "Christopher"
date: '2022-07-12'
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(viridis)
library(readxl)
library(plotly)

```

```{r}
soil_quality <- read_excel("C:/Users/Christopher Vest/Documents/Land_use_project/2022_DSPG_Landuse/Review/Christopher/soil_quality/Soil_Quality_Analysis.xlsx")

```

```{r Goochland}
g <- ggplot(soil_quality, aes(x = `G_Value`, y = `G_Area_acre`, fill = `G_Area_acre`)) + geom_bar(stat = "identity", aes(text = paste0(`G_Value`, "\n", "Total Acres: ", round(`G_Area_acre`, 0)))) + coord_flip() + theme(legend.position = "none") + scale_x_discrete(limits = rev) + scale_fill_viridis() + labs( title = "Total Acreage by Soil Quality Classification", y = "Acreage", x = "Soil Quality Classification")
ggplotly(g, tooltip = "text") %>%
  layout(annotations = list(x = 1, y = -0.1, text = "Source: NASS", showarrow = F, xref='paper', yref='paper', 
      xanchor='right', yanchor='auto'))
```

```{r Powhatan}
p <- ggplot(soil_quality, aes(x = `P_Value`, y = `P_Area_acre`, fill = `P_Area_acre`)) + geom_bar(stat = "identity", aes(text = paste0(`P_Value`, "\n", "Total Acres: ", round(`P_Area_acre`, 0))))+ geom_errorbarh(aes(xmax=as.numeric(`P_Value`)+0.45,xmin=as.numeric(`P_Value`)-0.45,height=0),position=position_dodge(width=0.9)) + coord_flip() + theme(legend.position = "none") + scale_x_discrete(limits = rev) +   scale_fill_viridis() + labs( title = "Total Acreage by Soil Quality Classification", y = "Acreage", x = "Soil Quality Classification")
#check source??
ggplotly(p, tooltip = "text") %>%
  layout(annotations = list(x = 1, y = -0.1, text = "Source: NASS", showarrow = F, xref='paper', yref='paper', 
      xanchor='right', yanchor='auto'))
```