---
title: "Relabelling Land Uses"
author: "JAM"
date: '2022-06-29'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(writexl)
library(foreign)
library(plyr)
library(dplyr)

library(RColorBrewer)
library(traveltime)
library(tidyverse)
library(tidycensus)
library(sf)
library(osmdata)
library(leaflet)
library(sp)
library(purrr)
library(mapview)
library(osrm)
library(rmapzen)
library(rgdal)
library(ggplot2)
library(scales)
library(nycflights13)
library(readxl)
library(rgdal)
```

```{r setting working directory and importing data}
setwd("C:/Users/malla/OneDrive/Desktop/DSPG/2022_DSPG_landuse")

# MASTER
master_label <- read_excel("LUC_codes/LUC_codeToName.xlsx", sheet = "codeToName")

## POWHATAN ============================================
pow_relabel <- read_excel("LUC_codes/LUC_codeToName.xlsx", sheet = "Powhatan")

### PARCELS ============================================

PowReduParc2021 <- st_read("Powhatan_Parcel_Data/Powhatan_Reduced_Data/PowReduTaxParcels2021.shp") %>% st_transform(crs = st_crs("EPSG:4326"))
PowReduParc2020 <- st_read("Powhatan_Parcel_Data/Powhatan_Reduced_Data/PowReduTaxParcels2020.shp") %>% st_transform(crs = st_crs("EPSG:4326"))
PowReduParc2019 <- st_read("Powhatan_Parcel_Data/Powhatan_Reduced_Data/PowReduTaxParcels2019.shp") %>% st_transform(crs = st_crs("EPSG:4326"))
PowReduParc2018 <- st_read("Powhatan_Parcel_Data/Powhatan_Reduced_Data/PowReduTaxParcels2018.shp") %>% st_transform(crs = st_crs("EPSG:4326"))
PowReduParc2017 <- st_read("Powhatan_Parcel_Data/Powhatan_Reduced_Data/PowReduTaxParcels2017.shp") %>% st_transform(crs = st_crs("EPSG:4326"))
PowReduParc2016 <- st_read("Powhatan_Parcel_Data/Powhatan_Reduced_Data/PowReduTaxParcels2016.shp") %>% st_transform(crs = st_crs("EPSG:4326"))
PowReduParc2015 <- st_read("Powhatan_Parcel_Data/Powhatan_Reduced_Data/PowReduTaxParcels2015.shp") %>% st_transform(crs = st_crs("EPSG:4326"))
PowReduParc2014 <- st_read("Powhatan_Parcel_Data/Powhatan_Reduced_Data/PowReduTaxParcels2014.shp") %>% st_transform(crs = st_crs("EPSG:4326"))
PowReduParc2013 <- st_read("Powhatan_Parcel_Data/Powhatan_Reduced_Data/PowReduTaxParcels2013.shp") %>% st_transform(crs = st_crs("EPSG:4326"))
PowReduParc2012 <- st_read("Powhatan_Parcel_Data/Powhatan_Reduced_Data/PowReduTaxParcels2012.shp") %>% st_transform(crs = st_crs("EPSG:4326"))

### PARCELLATION =======================================

PowParcellation_12_21 <- st_read("Powhatan_Parcel_Data/Powhatan_Parcellation/Pow_12_21_all_parcellation.shp") %>% st_transform(crs = st_crs("EPSG:4326"))
PowParcellation_12_13 <- st_read("Powhatan_Parcel_Data/Powhatan_Parcellation/Pow_13_12_parcellation.shp") %>% st_transform(crs = st_crs("EPSG:4326"))
PowParcellation_13_14 <- st_read("Powhatan_Parcel_Data/Powhatan_Parcellation/Pow_14_13_parcellation.shp") %>% st_transform(crs = st_crs("EPSG:4326"))
PowParcellation_14_15 <- st_read("Powhatan_Parcel_Data/Powhatan_Parcellation/Pow_15_14_parcellation.shp") %>% st_transform(crs = st_crs("EPSG:4326"))
PowParcellation_15_16 <- st_read("Powhatan_Parcel_Data/Powhatan_Parcellation/Pow_16_15_parcellation.shp") %>% st_transform(crs = st_crs("EPSG:4326"))
PowParcellation_16_17 <- st_read("Powhatan_Parcel_Data/Powhatan_Parcellation/Pow_17_16_parcellation.shp") %>% st_transform(crs = st_crs("EPSG:4326"))
PowParcellation_17_18 <- st_read("Powhatan_Parcel_Data/Powhatan_Parcellation/Pow_18_17_parcellation.shp") %>% st_transform(crs = st_crs("EPSG:4326"))
PowParcellation_18_19 <- st_read("Powhatan_Parcel_Data/Powhatan_Parcellation/Pow_19_18_parcellation.shp") %>% st_transform(crs = st_crs("EPSG:4326"))
PowParcellation_19_20 <- st_read("Powhatan_Parcel_Data/Powhatan_Parcellation/Pow_20_19_parcellation.shp") %>% st_transform(crs = st_crs("EPSG:4326"))
PowParcellation_20_21 <- st_read("Powhatan_Parcel_Data/Powhatan_Parcellation/Pow_21_20_parcellation.shp") %>% st_transform(crs = st_crs("EPSG:4326"))

## GOOCHLAND ============================================

### PARCELS ============================================

### PARCELLATION =======================================
```




POWHATAN PARCEL
```{r POWHATAN PARCEL}

View(PowReduParc2012)

# ================================================== 2012 =========================
fac.2012 <- PowReduParc2012$MLUSE
fac.2012[is.na(fac.2012)] <- 0
fac.2012 <- factor(fac.2012)
remap.2012 <- mapvalues(fac.2012, pow_relabel$pow_value, pow_relabel$pow_code)
remap.2012 <- mapvalues(remap.2012, master_label$code_value, master_label$code_name)

# ================================================== 2013 =========================
fac.2013 <- PowReduParc2013$MLUSE
fac.2013[is.na(fac.2013)] <- 0
fac.2013[fac.2013 == "02"] <- 2
fac.2013 <- factor(fac.2013)
remap.2013 <- mapvalues(fac.2013, pow_relabel$pow_value, pow_relabel$pow_code)
remap.2013 <- mapvalues(remap.2013, master_label$code_value, master_label$code_name)

# ================================================== 2014 =========================
fac.2014 <- PowReduParc2014$MLUSE
fac.2014[is.na(fac.2014)] <- 0
fac.2014 <- factor(fac.2014)
remap.2014 <- mapvalues(fac.2014, pow_relabel$pow_value, pow_relabel$pow_code)
remap.2014 <- mapvalues(remap.2014, master_label$code_value, master_label$code_name)

# ================================================== 2015 =========================
fac.2015 <- PowReduParc2015$MLUSE
fac.2015[is.na(fac.2015)] <- 0
fac.2015 <- factor(fac.2015)
remap.2015 <- mapvalues(fac.2015, pow_relabel$pow_value, pow_relabel$pow_code)
remap.2015 <- mapvalues(remap.2015, master_label$code_value, master_label$code_name)

# ================================================== 2016 =========================
fac.2016 <- PowReduParc2016$MLUSE
fac.2016[is.na(fac.2016)] <- 0
fac.2016 <- factor(fac.2016)
remap.2016 <- mapvalues(fac.2016, pow_relabel$pow_value, pow_relabel$pow_code)
remap.2016 <- mapvalues(remap.2016, master_label$code_value, master_label$code_name)

# ================================================== 2017 =========================
fac.2017 <- PowReduParc2017$MLUSE
fac.2017[is.na(fac.2017)] <- 0
fac.2017 <- factor(fac.2017)
remap.2017 <- mapvalues(fac.2017, pow_relabel$pow_value, pow_relabel$pow_code)
remap.2017 <- mapvalues(remap.2017, master_label$code_value, master_label$code_name)

# ================================================== 2018 =========================
fac.2018 <- PowReduParc2018$MLUSE
fac.2018[is.na(fac.2018)] <- 0
fac.2018 <- factor(fac.2018)
remap.2018 <- mapvalues(fac.2018, pow_relabel$pow_value, pow_relabel$pow_code)
remap.2018 <- mapvalues(remap.2018, master_label$code_value, master_label$code_name)

# ================================================== 2019 =========================
fac.2019 <- PowReduParc2019$MLUSE
fac.2019[is.na(fac.2019)] <- 0
fac.2019 <- factor(fac.2019)
remap.2019 <- mapvalues(fac.2019, pow_relabel$pow_value, pow_relabel$pow_code)
remap.2019 <- mapvalues(remap.2019, master_label$code_value, master_label$code_name)

# ================================================== 2020 =========================
fac.2020 <- PowReduParc2020$MLUSE
fac.2020[is.na(fac.2020)] <- 0
fac.2020[fac.2020 == "06"] <- 6
fac.2020 <- factor(fac.2020)
remap.2020 <- mapvalues(fac.2020, pow_relabel$pow_value, pow_relabel$pow_code)
remap.2020 <- mapvalues(remap.2020, master_label$code_value, master_label$code_name)

# ================================================== 2021 =========================
fac.2021 <- PowReduParc2021$MLUSE
fac.2021[is.na(fac.2021)] <- 0
fac.2021 <- factor(fac.2021)
remap.2021 <- mapvalues(fac.2021, pow_relabel$pow_value, pow_relabel$pow_code)
remap.2021 <- mapvalues(remap.2021, master_label$code_value, master_label$code_name)

# ================================================== OVER WRITING =================

PowReduParc2012$FIN_MLUSE <- remap.2012
PowReduParc2013$FIN_MLUSE <- remap.2013
PowReduParc2014$FIN_MLUSE <- remap.2014
PowReduParc2015$FIN_MLUSE <- remap.2015
PowReduParc2016$FIN_MLUSE <- remap.2016
PowReduParc2017$FIN_MLUSE <- remap.2017
PowReduParc2018$FIN_MLUSE <- remap.2018
PowReduParc2019$FIN_MLUSE <- remap.2019
PowReduParc2020$FIN_MLUSE <- remap.2020
PowReduParc2021$FIN_MLUSE <- remap.2021


# ================================================== SAVING =================

fileDir <- paste0(getwd(), "/Powhatan_Parcel_Data/Powhatan_Reduced_Data_FIN/")

st_write(PowReduParc2012, paste0(fileDir, "PowReduTaxParcels2012FIN.shp"))
st_write(PowReduParc2013, paste0(fileDir, "PowReduTaxParcels2013FIN.shp"))
st_write(PowReduParc2014, paste0(fileDir, "PowReduTaxParcels2014FIN.shp"))
st_write(PowReduParc2015, paste0(fileDir, "PowReduTaxParcels2015FIN.shp"))
st_write(PowReduParc2016, paste0(fileDir, "PowReduTaxParcels2016FIN.shp"))
st_write(PowReduParc2017, paste0(fileDir, "PowReduTaxParcels2017FIN.shp"))
st_write(PowReduParc2018, paste0(fileDir, "PowReduTaxParcels2018FIN.shp"))
st_write(PowReduParc2019, paste0(fileDir, "PowReduTaxParcels2019FIN.shp"))
st_write(PowReduParc2020, paste0(fileDir, "PowReduTaxParcels2020FIN.shp"))
st_write(PowReduParc2021, paste0(fileDir, "PowReduTaxParcels2021FIN.shp"))
```


```{r POWHATAN PARCELLATION}

# ================================================== 2012 - 2021 =========================
fac.all.prev <- PowParcellation_12_21$MLUSE_1
fac.all.prev[is.na(fac.all.prev)] <- 0
fac.all.prev <- factor(fac.all.prev)
remap.all.prev <- mapvalues(fac.all.prev, pow_relabel$pow_value, pow_relabel$pow_code)
remap.all.prev <- mapvalues(remap.all.prev, master_label$code_value, master_label$code_name)


fac.all.post <- PowParcellation_12_21$MLUSE
fac.all.post[is.na(fac.all.post)] <- 0
fac.all.post <- factor(fac.all.post)
remap.all.post <- mapvalues(fac.all.post, pow_relabel$pow_value, pow_relabel$pow_code)
remap.all.post <- mapvalues(remap.all.post, master_label$code_value, master_label$code_name)

# ================================================== 2012 - 2013 =========================
fac.2012.prev <- PowParcellation_12_13$MLUSE_1
fac.2012.prev[is.na(fac.2012.prev)] <- 0
fac.2012.prev <- factor(fac.2012.prev)
remap.2012.prev <- mapvalues(fac.2012.prev, pow_relabel$pow_value, pow_relabel$pow_code)
remap.2012.prev <- mapvalues(remap.2012.prev, master_label$code_value, master_label$code_name)

fac.2013.post <- PowParcellation_12_13$MLUSE
fac.2013.post[is.na(fac.2013.post)] <- 0
fac.2013.post <- factor(fac.2013.post)
remap.2013.post <- mapvalues(fac.2013.post, pow_relabel$pow_value, pow_relabel$pow_code)
remap.2013.post <- mapvalues(remap.2013.post, master_label$code_value, master_label$code_name)

# ================================================== 2013 - 2014 =========================
fac.2013.prev <- PowParcellation_13_14$MLUSE_1
fac.2013.prev[is.na(fac.2013.prev)] <- 0
fac.2013.prev <- factor(fac.2013.prev)
remap.2013.prev <- mapvalues(fac.2013.prev, pow_relabel$pow_value, pow_relabel$pow_code)
remap.2013.prev <- mapvalues(remap.2013.prev, master_label$code_value, master_label$code_name)

fac.2014.post <- PowParcellation_13_14$MLUSE
fac.2014.post[is.na(fac.2014.post)] <- 0
fac.2014.post <- factor(fac.2014.post)
remap.2014.post <- mapvalues(fac.2014.post, pow_relabel$pow_value, pow_relabel$pow_code)
remap.2014.post <- mapvalues(remap.2014.post, master_label$code_value, master_label$code_name)

# ================================================== 2014 - 2015 =========================
fac.2014.prev <- PowParcellation_14_15$MLUSE_1
fac.2014.prev[is.na(fac.2014.prev)] <- 0
fac.2014.prev <- factor(fac.2014.prev)
remap.2014.prev <- mapvalues(fac.2014.prev, pow_relabel$pow_value, pow_relabel$pow_code)
remap.2014.prev <- mapvalues(remap.2014.prev, master_label$code_value, master_label$code_name)

fac.2015.post <- PowParcellation_14_15$MLUSE
fac.2015.post[is.na(fac.2015.post)] <- 0
fac.2015.post <- factor(fac.2015.post)
remap.2015.post <- mapvalues(fac.2015.post, pow_relabel$pow_value, pow_relabel$pow_code)
remap.2015.post <- mapvalues(remap.2015.post, master_label$code_value, master_label$code_name)

# ================================================== 2015 - 2016 =========================
fac.2015.prev <- PowParcellation_15_16$MLUSE_1
fac.2015.prev[is.na(fac.2015.prev)] <- 0
fac.2015.prev <- factor(fac.2015.prev)
remap.2015.prev <- mapvalues(fac.2015.prev, pow_relabel$pow_value, pow_relabel$pow_code)
remap.2015.prev <- mapvalues(remap.2015.prev, master_label$code_value, master_label$code_name)

fac.2016.post <- PowParcellation_15_16$MLUSE
fac.2016.post[is.na(fac.2016.post)] <- 0
fac.2016.post <- factor(fac.2016.post)
remap.2016.post <- mapvalues(fac.2016.post, pow_relabel$pow_value, pow_relabel$pow_code)
remap.2016.post <- mapvalues(remap.2016.post, master_label$code_value, master_label$code_name)

# ================================================== 2016 - 2017 =========================
fac.2016.prev <- PowParcellation_16_17$MLUSE_1
fac.2016.prev[is.na(fac.2016.prev)] <- 0
fac.2016.prev <- factor(fac.2016.prev)
remap.2016.prev <- mapvalues(fac.2016.prev, pow_relabel$pow_value, pow_relabel$pow_code)
remap.2016.prev <- mapvalues(remap.2016.prev, master_label$code_value, master_label$code_name)

fac.2017.post <- PowParcellation_16_17$MLUSE
fac.2017.post[is.na(fac.2017.post)] <- 0
fac.2017.post <- factor(fac.2017.post)
remap.2017.post <- mapvalues(fac.2017.post, pow_relabel$pow_value, pow_relabel$pow_code)
remap.2017.post <- mapvalues(remap.2017.post, master_label$code_value, master_label$code_name)

# ================================================== 2017 - 2018 =========================
fac.2017.prev <- PowParcellation_17_18$MLUSE_1
fac.2017.prev[is.na(fac.2016.prev)] <- 0
fac.2017.prev <- factor(fac.2016.prev)
remap.2017.prev <- mapvalues(fac.2016.prev, pow_relabel$pow_value, pow_relabel$pow_code)
remap.2017.prev <- mapvalues(remap.2016.prev, master_label$code_value, master_label$code_name)

fac.2018.post <- PowParcellation_17_18$MLUSE
fac.2018.post[is.na(fac.2018.post)] <- 0
fac.2018.post <- factor(fac.2018.post)
remap.2018.post <- mapvalues(fac.2018.post, pow_relabel$pow_value, pow_relabel$pow_code)
remap.2018.post <- mapvalues(remap.2018.post, master_label$code_value, master_label$code_name)

# ================================================== 2018 - 2019 =========================
fac.2018.prev <- PowParcellation_18_19$MLUSE_1
fac.2018.prev[is.na(fac.2018.prev)] <- 0
fac.2018.prev <- factor(fac.2018.prev)
remap.2018.prev <- mapvalues(fac.2018.prev, pow_relabel$pow_value, pow_relabel$pow_code)
remap.2018.prev <- mapvalues(remap.2018.prev, master_label$code_value, master_label$code_name)

fac.2019.post <- PowParcellation_18_19$MLUSE
fac.2019.post[is.na(fac.2019.post)] <- 0
fac.2019.post <- factor(fac.2019.post)
remap.2019.post <- mapvalues(fac.2019.post, pow_relabel$pow_value, pow_relabel$pow_code)
remap.2019.post <- mapvalues(remap.2019.post, master_label$code_value, master_label$code_name)

# ================================================== 2019 - 2020 =========================
fac.2019.prev <- PowParcellation_19_20$MLUSE_1
fac.2019.prev[is.na(fac.2019.prev)] <- 0
fac.2019.prev <- factor(fac.2019.prev)
remap.2019.prev <- mapvalues(fac.2019.prev, pow_relabel$pow_value, pow_relabel$pow_code)
remap.2019.prev <- mapvalues(remap.2019.prev, master_label$code_value, master_label$code_name)

fac.2020.post <- PowParcellation_19_20$MLUSE
fac.2020.post[is.na(fac.2020.post)] <- 0
fac.2020.post <- factor(fac.2020.post)
remap.2020.post <- mapvalues(fac.2020.post, pow_relabel$pow_value, pow_relabel$pow_code)
remap.2020.post <- mapvalues(remap.2020.post, master_label$code_value, master_label$code_name)

# ================================================== 2020 - 2021 =========================
fac.2020.prev <- PowParcellation_20_21$MLUSE_1
fac.2020.prev[is.na(fac.2020.prev)] <- 0
fac.2020.prev <- factor(fac.2020.prev)
remap.2020.prev <- mapvalues(fac.2020.prev, pow_relabel$pow_value, pow_relabel$pow_code)
remap.2020.prev <- mapvalues(remap.2020.prev, master_label$code_value, master_label$code_name)

fac.2021.post <- PowParcellation_20_21$MLUSE
fac.2021.post[is.na(fac.2021.post)] <- 0
fac.2021.post <- factor(fac.2021.post)
remap.2021.post <- mapvalues(fac.2021.post, pow_relabel$pow_value, pow_relabel$pow_code)
remap.2021.post <- mapvalues(remap.2021.post, master_label$code_value, master_label$code_name)
  
# ================================================== OVER WRITING =================

PowParcellation_12_21$MLUSE_old <- remap.all.prev
PowParcellation_12_21$MLUSE_new <- remap.all.post

PowParcellation_12_13$MLUSE_old <- remap.2012.prev
PowParcellation_12_13$MLUSE_new <- remap.2013.post

PowParcellation_13_14$MLUSE_old <- remap.2013.prev
PowParcellation_13_14$MLUSE_new <- remap.2014.post

PowParcellation_14_15$MLUSE_old <- remap.2014.prev
PowParcellation_14_15$MLUSE_new <- remap.2015.post

PowParcellation_15_16$MLUSE_old <- remap.2015.prev
PowParcellation_15_16$MLUSE_new <- remap.2016.post

PowParcellation_16_17$MLUSE_old <- remap.2016.prev
PowParcellation_16_17$MLUSE_new <- remap.2017.post

PowParcellation_17_18$MLUSE_old <- remap.2017.prev
PowParcellation_17_18$MLUSE_new <- remap.2018.post

PowParcellation_18_19$MLUSE_old <- remap.2018.prev
PowParcellation_18_19$MLUSE_new <- remap.2019.post

PowParcellation_19_20$MLUSE_old <- remap.2019.prev
PowParcellation_19_20$MLUSE_new <- remap.2020.post

PowParcellation_20_21$MLUSE_old <- remap.2020.prev
PowParcellation_20_21$MLUSE_new <- remap.2021.post


# ================================================== SAVING =================

fileDir <- paste0(getwd(), "/Powhatan_Parcel_Data/Powhatan_Parcellation_FIN/")

st_write(PowParcellation_12_21, paste0(fileDir, "Pow_12_21_parcellationFIN.shp"))
st_write(PowParcellation_12_13, paste0(fileDir, "Pow_13_12_parcellationFIN.shp"))
st_write(PowParcellation_13_14, paste0(fileDir, "Pow_14_13_parcellationFIN.shp"))
st_write(PowParcellation_14_15, paste0(fileDir, "Pow_15_14_parcellationFIN.shp"))
st_write(PowParcellation_15_16, paste0(fileDir, "Pow_16_15_parcellationFIN.shp"))
st_write(PowParcellation_16_17, paste0(fileDir, "Pow_17_16_parcellationFIN.shp"))
st_write(PowParcellation_17_18, paste0(fileDir, "Pow_18_17_parcellationFIN.shp"))
st_write(PowParcellation_18_19, paste0(fileDir, "Pow_19_18_parcellationFIN.shp"))
st_write(PowParcellation_19_20, paste0(fileDir, "Pow_20_19_parcellationFIN.shp"))
st_write(PowParcellation_20_21, paste0(fileDir, "Pow_21_20_parcellationFIN.shp"))
```

