---
title: "ACS_visuals"
author: "JAM"
date: '2022-06-23'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tigris)
library(dplyr)
library(leaflet)
library(tidycensus)
library(tidyverse)
library(dplyr)
library(stringr)
library(tigris)
library(ggplot2)
library(viridis)
library(readxl)
library(gridExtra)
library(RColorBrewer)
library(ggpubr)
library(plotly)
options(scipen=999)
```

```{r reading in data}
parcel2012 <- read_xlsx(paste0(getwd(), "/LUC_codes/Cleaned_Parcel_Data/Tax_Par_2012CLEANED.xlsx"))
parcel2021 <- read_xlsx(paste0(getwd(), "/LUC_codes/Cleaned_Parcel_Data/Tax_Par_2021CLEANED.xlsx"))

# Setting MLUSE to a factor so we don't have to worry about it later.

parcel2012$MLUSE <- factor(parcel2012$MLUSE, 
                               levels = c("Single Family Residential Urban",
                                          "Single Family Residential Suburban",
                                          "Multi-Family Residential",
                                          "Commerical / Industrial",
                                          "Agricultural / Undeveloped (20-99 Acres)",
                                          "Agricultural / Undeveloped (100+ Acres)",
                                          "Other"))
parcel2021$MLUSE <- factor(parcel2021$MLUSE, 
                               levels = c("Single Family Residential Urban",
                                          "Single Family Residential Suburban",
                                          "Multi-Family Residential",
                                          "Commerical / Industrial",
                                          "Agricultural / Undeveloped (20-99 Acres)",
                                          "Agricultural / Undeveloped (100+ Acres)",
                                          "Other"))
```

```{r looking at MLUSE distributions}

parcel12.df <- parcel2012 %>% select(MLUSE, Area_ACRE)
parcel12.df <- rbind(parcel12.df, data.frame(MLUSE = "Multi-Family Residential", Area_ACRE = 0))

parcel12.df <- parcel12.df %>% 
  group_by(MLUSE) %>% 
  summarise(MLUSE_Total_Acres = sum(Area_ACRE), MLUSE_Count = length(MLUSE))


parcel21.df <- parcel2021 %>% select(MLUSE, Area_ACRE)

parcel21.df <- parcel21.df %>% 
  group_by(MLUSE) %>% 
  summarise(MLUSE_Total_Acres = sum(Area_ACRE), MLUSE_Count = length(MLUSE))




p12 <- ggplot(parcel12.df, aes(x = MLUSE, y = MLUSE_Total_Acres, fill = MLUSE)) + 
  geom_bar(stat = "identity") + 
  scale_fill_viridis_d() + 
  coord_flip() + 
  scale_y_reverse() + 
  labs(title = "Acres per Land use (2012)", x = "", y = "Acres", fill = "Land Use") + 
  geom_text(aes(label = round(MLUSE_Total_Acres,2)), hjust = 1.05) +
  theme(plot.title = element_text(hjust = 1), legend.position="none") + 
  scale_x_discrete(position = "top")+
  ylim(66000, 0)
  

p21 <- ggplot(parcel21.df, aes(x = MLUSE, y = MLUSE_Total_Acres, fill = MLUSE)) + 
  geom_bar(stat = "identity") + 
  scale_fill_viridis_d() + 
  coord_flip() + 
  theme(legend.position = "none", axis.text.y = element_blank()) + 
  labs(title = "Acres per Land use (2021)", x = "", y = "Acres", caption = "Source: Administrative Data from Powhatan County") +
  geom_text(aes(label = round(MLUSE_Total_Acres,2)), hjust = -.05) +
  ylim(0, 66000)

# ggarrange(p12, p21, ncol=2, common.legend=FALSE, labels=NULL)

grid.arrange(p12, p21, ncol=2, top = "Total Acres by land use (2012 vs. 2021)")



p12
p21
```


```{r plotting mean land values per acre}


parcel12.df <- parcel2012 %>% 
  select(MLUSE, MTOTPR) %>%
  group_by(MLUSE) %>%
  summarise(MLUSE_Mean_Cost = mean(MTOTPR))

p12 <- ggplot(parcel12.df, aes(x = MLUSE, y = MLUSE_Mean_Cost, fill = MLUSE)) + 
  geom_bar(stat = "identity") + 
  scale_fill_viridis_d() +
  theme(legend.position = "none") + 
  geom_text(aes(label = round(MLUSE_Mean_Cost,2)), vjust = -.3) +
  labs(title = "Mean Cost of Land by Land Value (2012)", caption = "Source: Administrative Data from Powhatan County", x = "Land Use", y = "Mean Cost")

parcel21.df <- parcel2021 %>%
  select(MLUSE, MTOTPR) %>%
  group_by(MLUSE) %>%
  summarise(MLUSE_Mean_Cost = mean(MTOTPR))

p21 <- ggplot(parcel21.df, aes(x = MLUSE, y = MLUSE_Mean_Cost, fill = MLUSE)) + 
  geom_bar(stat = "identity") + 
  scale_fill_viridis_d() +
  theme(legend.position = "none") + 
  geom_text(aes(label = round(MLUSE_Mean_Cost,2)), vjust = -.3) +
  labs(title = "Mean Cost of Land by Land Value (2021)", caption = "Source: Administrative Data from Powhatan County", x = "Land Use", y = "Mean Cost")


p12
p21
```


```{r checking out a histogram of Area_ACRE}
parcel12.df <- parcel2012 %>%
  select(Area_ACRE)

p12 <- ggplot(parcel12.df, aes(x = Area_ACRE)) + geom_histogram()
# This doesn't really show much then

parcel21.df <- parcel2021 %>%
  select(Area_ACRE)

p21 <- ggplot(parcel21.df, aes(x = Area_ACRE)) + geom_histogram()


p12
p21
```


```{r Building values}

```



